### ISSUE TITLE
Does not seem to work with elixir 3.0.0

### ISSUE THREAD

**Issue by itrea** [CREEATION/laravel-elixir-jade#7]
I get this error when trying to implement laravel-elixir-jade into laravel with elixir 3.0.0
it works fine when using elixir 2.0.0

```
/Applications/MAMP/htdocs/github/laravel-test/node_modules/laravel-elixir-jade/index.js:59
    this.registerWatcher('jade', [
         ^
TypeError: undefined is not a function
    at Function.<anonymous> (/Applications/MAMP/htdocs/github/laravel-test/node_modules/laravel-elixir-jade/index.js:59:10)
    at Function.<anonymous> (/Applications/MAMP/htdocs/github/laravel-test/node_modules/laravel-elixir/index.js:46:18)
    at /Applications/MAMP/htdocs/github/laravel-test/gulpfile.js:6:9
    at Elixir (/Applications/MAMP/htdocs/github/laravel-test/node_modules/laravel-elixir/index.js:20:5)
    at Object.<anonymous> (/Applications/MAMP/htdocs/github/laravel-test/gulpfile.js:5:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by CREEATION** [comment]
As I myself don't use this anymore, could someone look into it?
I'm open for pull requests :)
