### PR TITLE
Refactor to support elixir 3.0.0

### LINKED ISSUE #7: Does not seem to work with elixir 3.0.0
I get this error when trying to implement laravel-elixir-jade into laravel with elixir 3.0.0
it works fine when using elixir 2.0.0

```
/Applications/MAMP/htdocs/github/laravel-test/node_modules/laravel-elixir-jade/index.js:59
    this.registerWatcher('jade', [
         ^
TypeError: undefined is not a function
    at Function.<anonymous> (/Applications/MAMP/htdocs/github/laravel-test/node_modules/laravel-elixir-jade/index.js:59:10)
    at Function.<anonymous> (/Applications/MAMP/htdocs/github/laravel-test/node_modules/laravel-elixir/index.js:46:18)
    at /Applications/MAMP/htdocs/github/laravel-test/gulpfile.js:6:9
    at Elixir (/Applications/MAMP/htdocs/github/laravel-test/node_modules/laravel-elixir/index.js:20:5)
    at Object.<anonymous> (/Applications/MAMP/htdocs/github/laravel-test/gulpfile.js:5:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

### PR DESCRIPTION
**Pull request by Oldenborg**
I want to resolve #7 with a bit of refactoring to support elixir 3.0.0

### CODE REVIEW

**Comment by slue** [comment]
Hi, can you also provide a new release to support elixir 3.0.0?

thanks, Christoph

**Comment by CREEATION** [comment]
npm updated.
